// Seed risk: calendar edits survive DB writes and reload, including hour and duration.
import { expect } from "@playwright/test";
import { test } from "./authenticated";
import { addEntry, nextWeekMonday } from "./helpers";
test("calendar entry CRUD and dashboard search persist across reloads", async ({ page }) => {
  const date = nextWeekMonday();
  await addEntry(page, { title: "Angielski", date, time: "09:00" });
  const entry = page.getByTestId("calendar-session");
  await expect(entry).toContainText("09:00–10:00");
  await entry.getByText("Edytuj zajęcie", { exact: true }).click();
  const form = page.getByRole("form", { name: "Edytuj Angielski", exact: true });
  await form.getByLabel("Nazwa zajęcia").fill("Angielski · rozmowa");
  await form.getByLabel("Godzina").fill("14:00");
  await form.getByLabel("Czas (min)").fill("90");
  await form.getByRole("button", { name: "Zapisz zmiany" }).click();
  await expect(page.getByTestId("flash-ok")).toHaveText("Zapisano zmiany");
  await page.reload();
  await expect(entry).toContainText("Angielski · rozmowa");
  await expect(entry).toContainText("14:00–15:30");
  await page.goto("/dashboard?week=" + date);
  await expect(page.getByTestId("session")).toContainText("Angielski · rozmowa");
  await page.getByRole("searchbox", { name: "Szukaj zajęcia" }).fill("nieistniejące");
  await page.getByRole("button", { name: "Filtruj" }).click();
  await expect(page.getByTestId("session")).toHaveCount(0);
  await page.getByRole("link", { name: "Wyczyść filtry" }).click();
  await expect(page.getByTestId("session")).toHaveCount(1);
  await page.getByRole("link", { name: "Szczegóły" }).click();
  await entry.getByRole("button", { name: "Usuń", exact: true }).click();
  await expect(page.getByTestId("flash-ok")).toHaveText("Usunięto sesję");
  await page.reload();
  await expect(entry).toHaveCount(0);
  await page.goto("/dashboard?week=" + date);
  await expect(page.getByTestId("session")).toHaveCount(0);
});
